
<style>
    .compact-list .list-group-item {
        padding: 0.5rem 1rem;
        font-size: 0.85rem;
    }
    .compact-list .card-header {
        padding: 0.4rem 1rem;
        font-size: 0.9rem;
    }
    .compact-list .card {
        margin-bottom: 0;
    }
    .compact-list .form-control {
        height: calc(1.5em + 0.75rem + 2px);
    }
    #calendar th, #calendar td {
     
        text-align: center;
        font-size: 0.85rem;
        cursor: pointer;
        position: relative;
    }
    #calendar-container  {
    padding-top: 0 !important;
    padding-bottom: 0 !important;
    
  }
    /* Custom styles for Select2 within the table */
    .select2-container--default .select2-selection--single {
        border: none;
        border-radius: 0;
        height: auto;
        padding: 0;
        background: transparent;
        line-height: 1;
    }
    .select2-container .select2-selection--single {
        height: auto;
    }
    /* Larger modal */
    .modal-xl {
        max-width: 95%;
    }
    .selected-employee {
        background-color: lightgrey;
    }
</style>


<div class="modal-content">
    <div class="modal-header">
        <h5 class="modal-title">Employee Schedule</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <div class="row">
            <div class="col-md-3 compact-list">
                <div class="card">
                    <div class="card-header">
                        <input type="text" id="employeeSearch" class="form-control" placeholder="Search employee">
                    </div>
                    <div class="card-body">
                      <ul class="list-group" id="employeeList" style="max-height: 500px; overflow-y: auto;">
                        <?php 
                          if(!empty($employees))
                          {
                        ?>
                            <?php 
                              foreach($employees as $employee)
                              {
                                
                            ?>
                                <li class="list-group-item" data-employee-id="<?=$employee->employee_id?>" style="cursor:pointer;"><?php echo $employee->first_name .' '.$employee->last_name; ?></li>
                            <?php 
                              }
                             
                            ?>
                        <?php 
                          }
                          else
                          { 
                        ?>
                            <li class="list-group-item">No employees found.</li>
                        <?php
                          }
                        ?>
                            
                        </ul>
                    </div>
                </div>
            </div>

            <div class="col-md-9">
                <div class="row mb-3">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Month</label>
                            <select id="monthSelect" class="form-control select2bs4">
                                <option value="1">January</option>
                                <option value="2">February</option>
                                <option value="3">March</option>
                                <option value="4">April</option>
                                <option value="5">May</option>
                                <option value="6">June</option>
                                <option value="7">July</option>
                                <option value="8">August</option>
                                <option value="9">September</option>
                                <option value="10">October</option>
                                <option value="11">November</option>
                                <option value="12">December</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Year</label>
                            <select id="yearSelect" class="form-control select2bs4">
                                <!-- Years generated by JavaScript -->
                            </select>
                        </div>
                    </div>
                </div>

                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Schedule</h3>
                    </div>
                    <div class="card-body calendar_view" id="calendar-container">
                        <table id="calendar" class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>Sun</th>
                                    <th>Mon</th>
                                    <th>Tue</th>
                                    <th>Wed</th>
                                    <th>Thu</th>
                                    <th>Fri</th>
                                    <th>Sat</th>
                                </tr>
                            </thead>
                            <tbody></tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    </div>
</div>

<script>
$(document).ready(function() {
    const now = new Date();
    const currentMonth = now.getMonth() +1;
    const currentYear = now.getFullYear();
    let selectedEmployeeId = null;

    // Populate year dropdown from 1991 to the current year
    for (let i = 1991; i <= currentYear; i++) {
        let isSelected = i === currentYear;
        $('#yearSelect').append($('<option>', { value: i, text: i, selected: isSelected }));
    }

    // Set the current month selected in the dropdown
    $('#monthSelect').val(currentMonth).trigger('change');

    function createCalendar(month, year, attendanceData) {
        const firstDay = new Date(year, month, 1).getDay();
        const daysInMonth = new Date(year, month + 1, 0).getDate();
        const tbody = $('#calendar tbody');
        tbody.empty();

        let date = 1;
        for (let i = 0; i < 6; i++) {
            const row = $('<tr>');
            for (let j = 0; j < 7; j++) {
                const cell = $('<td class="calendar-container">');
                if (i === 0 && j < firstDay) {
                    cell.append('&nbsp;');
                } else if (date <= daysInMonth) {
                    const dateSpan = $('<span>').css({
                        position: 'absolute',
                        left: '5px',
                        bottom: '5px',
                        fontSize: 'smaller'
                    }).text(date);

                    const selectHtml = `<select class='attendance-select' data-date='${year}-${month+1}-${date}' style='width: 100%;'>
                        <option value=''>Select Status</option>
                        <option value='1'>Present</option>
                        <option value='0'>Absent</option>
                        <option value='0.5'>Half Leave</option>
                        <option value='0.25'>One Forth Leave</option>
                    </select>`;

                    // Set the selected option based on attendanceData if available
                    if (attendanceData && attendanceData[date]) {
                        cell.append(selectHtml).append(dateSpan);
                        const status = attendanceData[date].attendance_status;
                        const statusClass = getStatusClass(status);
                        cell.find('.attendance-select').val(status).trigger('change');
                        cell.addClass(statusClass);
                    } else {
                        cell.append(selectHtml).append(dateSpan);
                    }
                    date++;
                }
                row.append(cell);
                if (date > daysInMonth) {
                    while (j < 6) {
                        row.append($('<td>').append('&nbsp;'));
                        j++;
                    }
                }
            }
            tbody.append(row);
        }

        // Initialize Select2 and setup change event
        $('.attendance-select').select2({
						minimumResultsForSearch: Infinity,
						dropdownAutoWidth: true,
						width: '100%'
				}).on('select2:select', function(e) {
						const value = $(this).val();
						let selectedDate = $(this).data('date');

						// Format the selectedDate to ensure month and date are two digits
						let dateParts = selectedDate.split('-');
						let year = dateParts[0];
						let month = dateParts[1].padStart(2, '0');
						let day = dateParts[2].padStart(2, '0');
						selectedDate = `${year}-${month}-${day}`;
						alert(selectedDate);
						$(this).closest('td').removeClass('present absent half-leave one-forth-leave').addClass(getStatusClass(value));
						updateCellBackground($(this).closest('td'), value);
						saveAttendanceStatus(selectedEmployeeId, selectedDate, value);  // Save the attendance status
				});


        // Function to determine the CSS class based on attendance status
        function getStatusClass(status) {
            switch (status) {
                case '1':
                    return 'present'; // CSS class for Present
                case '0':
                    return 'absent'; // CSS class for Absent
                case '0.5':
                    return 'half-leave'; // CSS class for Half Leave
                case '0.25':
                    return 'one-forth-leave'; // CSS class for One Forth Leave
                default:
                    return ''; // Default class
            }
        }

        // Function to update cell background based on selected value
        function updateCellBackground(cell, status) {
            const colorMap = {
                '1': 'green',     // Present
                '0': 'red',       // Absent
                '0.5': 'pink',    // Half Leave
                '0.25': 'pink'    // One Forth Leave
            };
            cell.css('background-color', colorMap[status] || 'transparent');
        }

        // Function to save attendance status via AJAX
        function saveAttendanceStatus(employeeId, date, status) {

            $.ajax({
                url: '<?= base_url('attendance/add/') ?>',
                type: 'POST',
                data: {
                    employee_id: employeeId,
                    attendance_date: date,
                    attendance_status: status,
                    '<?php echo $this->security->get_csrf_token_name(); ?>' : '<?php echo $this->security->get_csrf_hash(); ?>'
                },
                dataType: 'json',
                success: function(response) {
                    if(response.code === 1) {
                        console.log('Attendance status updated successfully');
                    } else {
                        console.log('Failed to update attendance status');
                    }
                },
                error: function(xhr, status, error) {
                    console.error('AJAX Error: ' + status + ' - ' + error);
                }
            });
        }
    }

    // Initial calendar creation and react to dropdown changes
    //createCalendar(currentMonth, currentYear);
    $('#monthSelect, #yearSelect').change(function() {
      
        if (selectedEmployeeId !== null) {
            loadEmployeeCalendar(selectedEmployeeId, $('#monthSelect').val(), $('#yearSelect').val());
        }
    });

    $('#employeeSearch').on('keyup', function() {
        const value = $(this).val().toLowerCase();
        $('#employeeList li').filter(function() {
            $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1);
        });
    });

    $('#employeeList').on('click', 'li', function() {
        selectedEmployeeId = $(this).data('employee-id');
        $('#employeeList li').removeClass('selected-employee');
        $(this).addClass('selected-employee');
        loadEmployeeCalendar(selectedEmployeeId, $('#monthSelect').val(), $('#yearSelect').val());
    });

    function loadEmployeeCalendar(employee_id, month, year) {
        $.ajax({
            url: '<?= base_url('attendance/get_calendar') ?>',
            type: 'POST',
            data: {
                employee_id: employee_id,
                month: month,
                year: year,
                '<?php echo $this->security->get_csrf_token_name(); ?>' : '<?php echo $this->security->get_csrf_hash(); ?>'
            },
            dataType: 'json',
            success: function(response) {
                $('.calendar_view').html(response.calendar_html);
            },
            error: function(xhr, status, error) {
                console.error('AJAX Error: ' + status + ' - ' + error);
            }
        });
    }
});
</script>











